name: Build binary

on:
  push:
    tags:
      - v**
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        
#         job:
#           - { os: macos-latest }
#           - { os: ubuntu-latest }
#           - { os: windows-latest }


    name: Build
    runs-on: ${{ matrix.job.os }}
    steps:
      - if: matrix.job.os == "ubuntu-latest"
        name: "Install ffmpeg for Ubuntu"
        run: apt install -y clang libavcodec-dev libavformat-dev libavutil-dev pkg-config
      - if: matrix.job.os == "macos-latest"
        name: "Install ffmpeg for macOS"
        run: brew install pkg-config ffmpeg
#       - if: matrix.job.os == "windows-latest"
#         name: "Install ffmpeg for Windows"
        
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        id: rename
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            BIN='villagers-embedding-tool_linux_amd64'
            mv target/release/villagers-embedding-tool target/release/$BIN
          elif [ "$RUNNER_OS" == "macOS" ]; then
            BIN='villagers-embedding-tool_darwin_amd64'
            mv target/release/villagers-embedding-tool target/release/$BIN
          else
            BIN='villagers-embedding-tool_windows_amd64.exe'
            mv target/release/villagers-embedding-tool.exe target/release/$BIN
          fi
          echo "::set-output name=bin::target/release/$BIN"
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            target/release/villagers-embedding-tool*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.rename.outputs.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
